name: Update Readwise Articles

on:
  schedule:
    # Define the schedule (e.g., daily at midnight UTC)
    - cron: '0 0 * * *'

jobs:
  update-readwise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Choose the appropriate Python version

      - name: Install dependencies
        run: pip install requests

      - name: Execute Python script
        run: |
          python update_readwise.py ${{ secrets.READWISE_API_KEY }}
      env:
        READWISE_API_KEY: ${{ secrets.READWISE_API_KEY }}
